version: '3.8'

services:
  app:
    build: .
    container_name: ci3-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    container_name: ci3-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci3db
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: sistem_sales_order
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
